# config/prd2wiki.yaml
server:
  addr: "0.0.0.0:8082"
  debug_addr: "0.0.0.0:6060"

data:
  dir: "./data"

tree:
  dir: "./tree"

librarian:
  socket: "/var/run/pippi-librarian.sock"

logging:
  level: "info"
